
theme = "slick"

[icons]
name = "awesome"
[icons.overrides]
cpu = ""
memory = ""

[[block]]
block = "cpu"
interval = 1
format = "cpu {utilization}%"

[[block]]
block = "memory"
format_mem = "mem {Mug} GB | {MAg} GB"
format_swap = "swp {SUg} GB / {STg} GB"
display_type = "memory"
icons = false
interval = 5

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
format = "{alias} {available} {unit}"

[[block]]
block = "net"
device = "wlp7s0"
format = "{ssid} {signal_strength} {ip}"
interval = 5
use_bits = false

[[block]]
block = "time"
interval = 30
format = "%a %y-%m-%d %R"

[[block]]
block = "sound"
driver = "alsa"

